# Generated by Django 5.2.4 on 2025-08-08 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Integrantes",
            fields=[
                (
                    "person_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
                ("sobrenome", models.CharField(max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Gerencia"),
                            ("LEAD", "Lider de Equipe"),
                            ("MEMBER", "Membro"),
                            ("GUEST", "Acesso Limitado"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("cargo", models.CharField(default="Desligado", max_length=35)),
                (
                    "equipe",
                    models.ForeignKey(
                        blank=True,
                        max_length=20,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.equipes",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipes",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_boss",
                to="projeto_crm_final.integrantes",
            ),
        ),
        migrations.AddField(
            model_name="equipes",
            name="membros",
            field=models.ManyToManyField(to="projeto_crm_final.integrantes"),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("onde", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("descricao", models.TextField(blank=True, max_length=300)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("dev", "dev"),
                            ("TI", "Tecnologia da Informação"),
                            ("MK", "Marketing"),
                            ("VD", "Vendas"),
                            ("FN", "Finanças"),
                            ("RH", "Recursos Humanos"),
                            ("CS", "Serviço ao Cliente"),
                            ("OP", "Operações"),
                            ("PD", "Pesquisa & Desenvolvimento"),
                            ("LG", "Logística"),
                            ("JR", "Jurídico"),
                        ],
                        default="dev",
                        max_length=100,
                    ),
                ),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("regular", "Regular"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("canceled", "Cancelado"),
                            ("overdue", "Data vencida"),
                            ("done", "Concluído"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("prazofinal", models.DateField()),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatorioProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="relatorios/")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("cloudinary_url", models.URLField(blank=True, null=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.projetos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarefas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Para fazer"),
                            ("doing", "Em andamento"),
                            ("done", "Feito"),
                            ("late", "Atrasada"),
                            ("canceled", "Cancelada"),
                        ],
                        default="todo",
                        max_length=15,
                    ),
                ),
                ("prazofinal", models.DateField()),
                (
                    "inicio",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("regular", "Regular"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.equipes",
                        verbose_name="Equipe Responsável",
                    ),
                ),
                (
                    "projetoparent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_do_projeto",
                        to="projeto_crm_final.projetos",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.integrantes",
                        verbose_name="Responsável Direto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["prazofinal"],
            },
        ),
        migrations.CreateModel(
            name="RelatorioTarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("arquivo", models.FileField(upload_to="relatorios_tarefas/")),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios",
                        to="projeto_crm_final.tarefas",
                    ),
                ),
            ],
        ),
    ]
