# Generated by Django 5.2.4 on 2025-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetos",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("regular", "Regular"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projetos",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("dev", "dev"),
                    ("TI", "Tecnologia da Informação"),
                    ("MK", "Marketing"),
                    ("VD", "Vendas"),
                    ("FN", "Finanças"),
                    ("RH", "Recursos Humanos"),
                    ("CS", "Serviço ao Cliente"),
                    ("OP", "Operações"),
                    ("PD", "Pesquisa & Desenvolvimento"),
                    ("LG", "Logística"),
                    ("JR", "Jurídico"),
                ],
                default="null",
                max_length=100,
            ),
        ),
    ]
