# Generated by Django 5.2.4 on 2025-08-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="cargo",
            field=models.CharField(default="Não definido", max_length=35),
        ),
    ]
