# Generated by Django 5.2.4 on 2025-07-26 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("dca0b529-8342-4206-bd1f-c64126df5db3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
