# Generated by Django 5.2.4 on 2025-08-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0002_projetos_prioridade_alter_projetos_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projetos",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("dev", "dev"),
                    ("TI", "Tecnologia da Informação"),
                    ("MK", "Marketing"),
                    ("VD", "Vendas"),
                    ("FN", "Finanças"),
                    ("RH", "Recursos Humanos"),
                    ("CS", "Serviço ao Cliente"),
                    ("OP", "Operações"),
                    ("PD", "Pesquisa & Desenvolvimento"),
                    ("LG", "Logística"),
                    ("JR", "Jurídico"),
                ],
                default="dev",
                max_length=100,
            ),
        ),
    ]
