# Generated by Django 5.2.4 on 2025-07-26 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0002_alter_integrantes_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("f37ac2ae-a6a2-4e04-bd77-34b947431014"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
