# Generated by Django 5.2.4 on 2025-07-26 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0003_alter_integrantes_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrantes",
            name="cargo",
            field=models.CharField(blank=True, default="Desligado", max_length=20),
        ),
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("c45fecb3-78b3-4bfd-9a19-f1b7283a37e8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
