# Generated by Django 5.2.4 on 2025-07-26 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0004_integrantes_cargo_alter_integrantes_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrantes",
            name="equipe",
            field=models.CharField(default="Sem equipe", max_length=20),
        ),
        migrations.AlterField(
            model_name="integrantes",
            name="cargo",
            field=models.CharField(default="Desligado", max_length=20),
        ),
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("dce07ea2-4469-4018-9ca5-560af494383a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
