# Generated by Django 5.2.4 on 2025-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0004_relatorioprojeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatorioprojeto",
            name="cloudinary_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
