# Generated by Django 5.2.4 on 2025-08-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0005_relatorioprojeto_cloudinary_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefas",
            options={
                "ordering": ["prazofinal"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
        migrations.RemoveField(
            model_name="tarefas",
            name="usuario",
        ),
        migrations.AddField(
            model_name="tarefas",
            name="atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AddField(
            model_name="tarefas",
            name="responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projeto_crm_final.integrantes",
                verbose_name="Responsável Direto",
            ),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto_crm_final.equipes",
                verbose_name="Equipe Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="inicio",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("regular", "Regular"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
    ]
