# Generated by Django 5.2.4 on 2025-07-28 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto_crm_final",
            "0005_integrantes_equipe_alter_integrantes_cargo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("20f0936f-0e0e-40a4-897a-10bb504be12f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("onde", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("membros", models.ManyToManyField(to="projeto_crm_final.integrantes")),
            ],
        ),
        migrations.CreateModel(
            name="Projetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("descricao", models.TextField(blank=True, max_length=300)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("null", "Não específico"), ("dev", "dev")],
                        default="null",
                        max_length=100,
                    ),
                ),
                ("inicio", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("canceled", "Cancelado"),
                            ("expired", "Data vencida"),
                            ("done", "Concluído"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("prazofinal", models.DateField()),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarefas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarefa", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Para fazer"),
                            ("analise", "Em analise"),
                            ("debater", "A debater"),
                            ("emandamento", "Em andamento"),
                            ("done", "Feito"),
                            ("late", "Atrasada"),
                            ("canceled", "Cancelada"),
                        ],
                        default="parafazer",
                        max_length=15,
                    ),
                ),
                ("prazofinal", models.DateField()),
                ("inicio", models.DateField(auto_now_add=True)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("regular", "Regular"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.equipes",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.projetos",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
            ],
        ),
    ]
