# Generated by Django 5.2.4 on 2025-07-29 01:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto_crm_final",
            "0006_alter_integrantes_person_id_auditlog_equipes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("ceec78d6-15bd-451a-82a1-3c8507e5cf70"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="projetos",
            name="inicio",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="projetos",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("canceled", "Cancelado"),
                    ("overdue", "Data vencida"),
                    ("done", "Concluído"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
