# Generated by Django 5.2.4 on 2025-08-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto_crm_final",
            "0006_alter_tarefas_options_remove_tarefas_usuario_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Para fazer"),
                    ("emandamento", "Em andamento"),
                    ("done", "Feito"),
                    ("late", "Atrasada"),
                    ("canceled", "Cancelada"),
                ],
                default="todo",
                max_length=15,
            ),
        ),
    ]
