# Generated by Django 5.2.4 on 2025-07-30 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto_crm_final",
            "0007_alter_integrantes_person_id_alter_projetos_inicio_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("c5a7585b-1d53-4742-8f0d-2bcd5b3050c5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
