# Generated by Django 5.2.4 on 2025-08-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0007_alter_tarefas_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetos",
            name="tarefas",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projeto_tarefas",
                to="projeto_crm_final.tarefas",
            ),
        ),
        migrations.AlterField(
            model_name="tarefas",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas_do_projeto",
                to="projeto_crm_final.projetos",
            ),
        ),
    ]
