# Generated by Django 5.2.4 on 2025-07-30 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0008_alter_integrantes_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("4ffda2d3-07a8-4f45-bb00-30f8f9d68679"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="projetos",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("null", "Não específico"),
                    ("dev", "dev"),
                    ("TI", "Tecnologia da Informação"),
                    ("MK", "Marketing"),
                    ("VD", "Vendas"),
                    ("FN", "Finanças"),
                    ("RH", "Recursos Humanos"),
                    ("CS", "Serviço ao Cliente"),
                    ("OP", "Operações"),
                    ("PD", "Pesquisa & Desenvolvimento"),
                    ("LG", "Logística"),
                    ("JR", "Jurídico"),
                ],
                default="null",
                max_length=100,
            ),
        ),
    ]
