# Generated by Django 5.2.4 on 2025-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0008_projetos_tarefas_alter_tarefas_projeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projetos",
            name="tarefas",
            field=models.ManyToManyField(
                blank=True,
                related_name="projeto_tarefas",
                to="projeto_crm_final.tarefas",
            ),
        ),
    ]
