# Generated by Django 5.2.4 on 2025-08-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0009_alter_projetos_tarefas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarefas",
            old_name="tarefa",
            new_name="name",
        ),
    ]
