# Generated by Django 5.2.4 on 2025-07-30 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto_crm_final",
            "0009_alter_integrantes_person_id_alter_projetos_categoria",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("943b150c-12ed-4602-af64-e6b28cfe2854"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
