# Generated by Django 5.2.4 on 2025-07-31 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0010_alter_integrantes_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantes",
            name="person_id",
            field=models.UUIDField(
                default=uuid.UUID("1434563b-2a98-406a-aeea-9500b0fa0ee6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
