# Generated by Django 5.2.4 on 2025-08-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0010_rename_tarefa_tarefas_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarefas",
            old_name="projeto",
            new_name="projetoparent",
        ),
    ]
