# Generated by Django 5.2.4 on 2025-08-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0011_rename_projeto_tarefas_projetoparent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projetos",
            name="tarefas",
        ),
    ]
