# Generated by Django 5.2.4 on 2025-08-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0012_remove_projetos_tarefas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projeto_crm_final.integrantes",
                verbose_name="Responsável Direto",
            ),
        ),
    ]
