# Generated by Django 5.2.4 on 2025-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0013_alter_tarefas_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefas",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Para fazer"),
                    ("doing", "Em andamento"),
                    ("done", "Feito"),
                    ("late", "Atrasada"),
                    ("canceled", "Cancelada"),
                ],
                default="todo",
                max_length=15,
            ),
        ),
    ]
