# Generated by Django 5.2.4 on 2025-08-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto_crm_final", "0014_alter_tarefas_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioTarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("arquivo", models.FileField(upload_to="relatorios_tarefas/")),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto_crm_final.integrantes",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatorios",
                        to="projeto_crm_final.tarefas",
                    ),
                ),
            ],
        ),
    ]
